### ISSUE TITLE
'Newton-Raphson algorithm failed to converge'

### ISSUE THREAD

**Issue by Mohit8982** [RayDeCampo/nodejs-xirr#14]
const cagr = xirr([
  { amount: -99995, when: new Date(2021, 7, 3)},
  { amount: 97642, when: new Date(2021, 7, 9) }
]);

console.log(cagr);

error : 

        throw new Error("Newton-Raphson algorithm failed to converge.");
        ^

Error: Newton-Raphson algorithm failed to converge.
    at xirr (D:\git_repos\elite_node\node_modules\xirr\xirr.js:121:15)
    at Object.<anonymous> (D:\git_repos\elite_node\code.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.0

**Comment by RayDeCampo** [comment]
This will converge if you supply a guess, see the associated commit
